pg:
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes:
    - ~/docker-data/postgres:/var/lib/postgresql/data:z
  environment:
    - POSTGRES_PASSWORD=dbpassword

user-notes:
  image: 9698629519/demo-registry:{{ .Env.USER_NOTE_VERSION }}
  ports:
    - "8080:8080"
  environment:
    - USER_NOTE_DB_HOST=pg
    - USER_NOTE_DB_PORT=5432
    - USER_NOTE_DB=usernotes
    - USER_NOTE_DB_USER=noteuser
    - USER_NOTE_DB_PASSWORD=password
    - _JAVA_OPTIONS=-Dlogging.level.com.user.notes=INFO -Dspring.profiles.active=dev
  links:
    - pg:pg
